### ISSUE TITLE
Puppet 3.x

### ISSUE THREAD

**Issue by agarbato** [jcustenborder/puppet-confluent#56]
Last master branch broke puppet 3.x compatibility 
Error 400 on SERVER: Syntax error at 'Integer'; expected ')'
Var type declaration only works with puppet 4.x

**Comment by jcustenborder** [comment]
@agarbato I'm not planning on supporting anything before puppet 4.x. I'm not sure if the future parser is available on 3.x. If you can enable that it might work.
